spawnPos = "TrafficLane.112" at 2;
goal = "TrafficLane.112" at 130;
route1 = [
    "TrafficLane.112" max-velocity(8.333)
];

npc1 = NPC("smallcar", spawnPos forward 16, goal, route1, 
    [acceleration(1), 
     deceleration(9.81), 
     aggressive-driving,
     delay-move-until-ego-engaged(1.5)]);

npc2 = NPC("smallcar", _, [delay-spawn(_)]);

ego = Ego(spawnPos, "TrafficLane.112" at 190, [max-velocity(8.666)]);

run(ego, [npc1,npc2], [saving-timeout(30)]);