//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ../grammar/AWSIMScriptGrammar.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class AWSIMScriptGrammarParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, STRING=29, SIGN=30, NUMBER=31, 
		ID=32, WS=33, LINE_COMMENT=34;
	public const int
		RULE_positionExp = 0, RULE_roadExp = 1, RULE_configExp = 2, RULE_vector2Exp = 3, 
		RULE_egoSettingExp = 4, RULE_simulationSettingExp = 5, RULE_functionExp = 6, 
		RULE_arrayExp = 7, RULE_argumentList = 8, RULE_assignmentStm = 9, RULE_variableExp = 10, 
		RULE_expression = 11, RULE_statement = 12, RULE_scenario = 13, RULE_stringExp = 14, 
		RULE_numberExp = 15, RULE_idExp = 16;
	public static readonly string[] ruleNames = {
		"positionExp", "roadExp", "configExp", "vector2Exp", "egoSettingExp", 
		"simulationSettingExp", "functionExp", "arrayExp", "argumentList", "assignmentStm", 
		"variableExp", "expression", "statement", "scenario", "stringExp", "numberExp", 
		"idExp"
	};

	private static readonly string[] _LiteralNames = {
		null, "'at'", "'back'", "'forward'", "'left'", "'right'", "'max-velocity'", 
		"'('", "')'", "'change-lane'", "'cut-in'", "'cut-out'", "'aggressive-driving'", 
		"'acceleration'", "'deceleration'", "'speed'", "'delay-spawn'", "'delay-move'", 
		"'delay-spawn-until-ego-move'", "'delay-move-until-ego-move'", "'delay-spawn-until-ego-engaged'", 
		"'delay-move-until-ego-engaged'", "'#'", "'saving-timeout'", "'['", "']'", 
		"','", "'='", "';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, "STRING", "SIGN", "NUMBER", "ID", "WS", 
		"LINE_COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "AWSIMScriptGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static AWSIMScriptGrammarParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public AWSIMScriptGrammarParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public AWSIMScriptGrammarParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class PositionExpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StringExpContext stringExp() {
			return GetRuleContext<StringExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpContext numberExp() {
			return GetRuleContext<NumberExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VariableExpContext[] variableExp() {
			return GetRuleContexts<VariableExpContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public VariableExpContext variableExp(int i) {
			return GetRuleContext<VariableExpContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PositionExpContext positionExp() {
			return GetRuleContext<PositionExpContext>(0);
		}
		public PositionExpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_positionExp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterPositionExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitPositionExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPositionExp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PositionExpContext positionExp() {
		return positionExp(0);
	}

	private PositionExpContext positionExp(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		PositionExpContext _localctx = new PositionExpContext(Context, _parentState);
		PositionExpContext _prevctx = _localctx;
		int _startState = 0;
		EnterRecursionRule(_localctx, 0, RULE_positionExp, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 67;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				{
				State = 35;
				stringExp();
				State = 41;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
				case 1:
					{
					State = 36;
					Match(T__0);
					State = 39;
					ErrorHandler.Sync(this);
					switch (TokenStream.LA(1)) {
					case NUMBER:
						{
						State = 37;
						numberExp();
						}
						break;
					case ID:
						{
						State = 38;
						variableExp();
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					}
					break;
				}
				}
				break;
			case 2:
				{
				State = 43;
				variableExp();
				State = 44;
				Match(T__1);
				State = 47;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case NUMBER:
					{
					State = 45;
					numberExp();
					}
					break;
				case ID:
					{
					State = 46;
					variableExp();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			case 3:
				{
				State = 49;
				variableExp();
				State = 50;
				Match(T__2);
				State = 53;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case NUMBER:
					{
					State = 51;
					numberExp();
					}
					break;
				case ID:
					{
					State = 52;
					variableExp();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			case 4:
				{
				State = 55;
				variableExp();
				State = 56;
				Match(T__3);
				State = 59;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case NUMBER:
					{
					State = 57;
					numberExp();
					}
					break;
				case ID:
					{
					State = 58;
					variableExp();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			case 5:
				{
				State = 61;
				variableExp();
				State = 62;
				Match(T__4);
				State = 65;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case NUMBER:
					{
					State = 63;
					numberExp();
					}
					break;
				case ID:
					{
					State = 64;
					variableExp();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 95;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 93;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
					case 1:
						{
						_localctx = new PositionExpContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_positionExp);
						State = 69;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 70;
						Match(T__1);
						State = 73;
						ErrorHandler.Sync(this);
						switch (TokenStream.LA(1)) {
						case NUMBER:
							{
							State = 71;
							numberExp();
							}
							break;
						case ID:
							{
							State = 72;
							variableExp();
							}
							break;
						default:
							throw new NoViableAltException(this);
						}
						}
						break;
					case 2:
						{
						_localctx = new PositionExpContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_positionExp);
						State = 75;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 76;
						Match(T__2);
						State = 79;
						ErrorHandler.Sync(this);
						switch (TokenStream.LA(1)) {
						case NUMBER:
							{
							State = 77;
							numberExp();
							}
							break;
						case ID:
							{
							State = 78;
							variableExp();
							}
							break;
						default:
							throw new NoViableAltException(this);
						}
						}
						break;
					case 3:
						{
						_localctx = new PositionExpContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_positionExp);
						State = 81;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 82;
						Match(T__3);
						State = 85;
						ErrorHandler.Sync(this);
						switch (TokenStream.LA(1)) {
						case NUMBER:
							{
							State = 83;
							numberExp();
							}
							break;
						case ID:
							{
							State = 84;
							variableExp();
							}
							break;
						default:
							throw new NoViableAltException(this);
						}
						}
						break;
					case 4:
						{
						_localctx = new PositionExpContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_positionExp);
						State = 87;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 88;
						Match(T__4);
						State = 91;
						ErrorHandler.Sync(this);
						switch (TokenStream.LA(1)) {
						case NUMBER:
							{
							State = 89;
							numberExp();
							}
							break;
						case ID:
							{
							State = 90;
							variableExp();
							}
							break;
						default:
							throw new NoViableAltException(this);
						}
						}
						break;
					}
					} 
				}
				State = 97;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class RoadExpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StringExpContext stringExp() {
			return GetRuleContext<StringExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpContext numberExp() {
			return GetRuleContext<NumberExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VariableExpContext variableExp() {
			return GetRuleContext<VariableExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentListContext argumentList() {
			return GetRuleContext<ArgumentListContext>(0);
		}
		public RoadExpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_roadExp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterRoadExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitRoadExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRoadExp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RoadExpContext roadExp() {
		RoadExpContext _localctx = new RoadExpContext(Context, State);
		EnterRule(_localctx, 2, RULE_roadExp);
		int _la;
		try {
			State = 127;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case STRING:
				EnterOuterAlt(_localctx, 1);
				{
				State = 98;
				stringExp();
				State = 107;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__5) {
					{
					State = 99;
					Match(T__5);
					State = 100;
					Match(T__6);
					State = 103;
					ErrorHandler.Sync(this);
					switch (TokenStream.LA(1)) {
					case NUMBER:
						{
						State = 101;
						numberExp();
						}
						break;
					case ID:
						{
						State = 102;
						variableExp();
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 105;
					Match(T__7);
					}
				}

				}
				break;
			case T__8:
				EnterOuterAlt(_localctx, 2);
				{
				State = 109;
				Match(T__8);
				State = 110;
				Match(T__6);
				State = 112;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 7008681536L) != 0)) {
					{
					State = 111;
					argumentList();
					}
				}

				State = 114;
				Match(T__7);
				}
				break;
			case T__9:
				EnterOuterAlt(_localctx, 3);
				{
				State = 115;
				Match(T__9);
				State = 116;
				Match(T__6);
				State = 118;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 7008681536L) != 0)) {
					{
					State = 117;
					argumentList();
					}
				}

				State = 120;
				Match(T__7);
				}
				break;
			case T__10:
				EnterOuterAlt(_localctx, 4);
				{
				State = 121;
				Match(T__10);
				State = 122;
				Match(T__6);
				State = 124;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 7008681536L) != 0)) {
					{
					State = 123;
					argumentList();
					}
				}

				State = 126;
				Match(T__7);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConfigExpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpContext numberExp() {
			return GetRuleContext<NumberExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VariableExpContext variableExp() {
			return GetRuleContext<VariableExpContext>(0);
		}
		public ConfigExpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_configExp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterConfigExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitConfigExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConfigExp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConfigExpContext configExp() {
		ConfigExpContext _localctx = new ConfigExpContext(Context, State);
		EnterRule(_localctx, 4, RULE_configExp);
		try {
			State = 202;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__11:
				EnterOuterAlt(_localctx, 1);
				{
				State = 129;
				Match(T__11);
				}
				break;
			case T__12:
				EnterOuterAlt(_localctx, 2);
				{
				State = 130;
				Match(T__12);
				State = 131;
				Match(T__6);
				State = 134;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case NUMBER:
					{
					State = 132;
					numberExp();
					}
					break;
				case ID:
					{
					State = 133;
					variableExp();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 136;
				Match(T__7);
				}
				break;
			case T__13:
				EnterOuterAlt(_localctx, 3);
				{
				State = 138;
				Match(T__13);
				State = 139;
				Match(T__6);
				State = 142;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case NUMBER:
					{
					State = 140;
					numberExp();
					}
					break;
				case ID:
					{
					State = 141;
					variableExp();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 144;
				Match(T__7);
				}
				break;
			case T__14:
				EnterOuterAlt(_localctx, 4);
				{
				State = 146;
				Match(T__14);
				State = 147;
				Match(T__6);
				State = 150;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case NUMBER:
					{
					State = 148;
					numberExp();
					}
					break;
				case ID:
					{
					State = 149;
					variableExp();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 152;
				Match(T__7);
				}
				break;
			case T__15:
				EnterOuterAlt(_localctx, 5);
				{
				State = 154;
				Match(T__15);
				State = 155;
				Match(T__6);
				State = 158;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case NUMBER:
					{
					State = 156;
					numberExp();
					}
					break;
				case ID:
					{
					State = 157;
					variableExp();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 160;
				Match(T__7);
				}
				break;
			case T__16:
				EnterOuterAlt(_localctx, 6);
				{
				State = 162;
				Match(T__16);
				State = 163;
				Match(T__6);
				State = 166;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case NUMBER:
					{
					State = 164;
					numberExp();
					}
					break;
				case ID:
					{
					State = 165;
					variableExp();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 168;
				Match(T__7);
				}
				break;
			case T__17:
				EnterOuterAlt(_localctx, 7);
				{
				State = 170;
				Match(T__17);
				State = 171;
				Match(T__6);
				State = 174;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case NUMBER:
					{
					State = 172;
					numberExp();
					}
					break;
				case ID:
					{
					State = 173;
					variableExp();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 176;
				Match(T__7);
				}
				break;
			case T__18:
				EnterOuterAlt(_localctx, 8);
				{
				State = 178;
				Match(T__18);
				State = 179;
				Match(T__6);
				State = 182;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case NUMBER:
					{
					State = 180;
					numberExp();
					}
					break;
				case ID:
					{
					State = 181;
					variableExp();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 184;
				Match(T__7);
				}
				break;
			case T__19:
				EnterOuterAlt(_localctx, 9);
				{
				State = 186;
				Match(T__19);
				State = 187;
				Match(T__6);
				State = 190;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case NUMBER:
					{
					State = 188;
					numberExp();
					}
					break;
				case ID:
					{
					State = 189;
					variableExp();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 192;
				Match(T__7);
				}
				break;
			case T__20:
				EnterOuterAlt(_localctx, 10);
				{
				State = 194;
				Match(T__20);
				State = 195;
				Match(T__6);
				State = 198;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case NUMBER:
					{
					State = 196;
					numberExp();
					}
					break;
				case ID:
					{
					State = 197;
					variableExp();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 200;
				Match(T__7);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Vector2ExpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpContext[] numberExp() {
			return GetRuleContexts<NumberExpContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpContext numberExp(int i) {
			return GetRuleContext<NumberExpContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VariableExpContext[] variableExp() {
			return GetRuleContexts<VariableExpContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public VariableExpContext variableExp(int i) {
			return GetRuleContext<VariableExpContext>(i);
		}
		public Vector2ExpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_vector2Exp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterVector2Exp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitVector2Exp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVector2Exp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Vector2ExpContext vector2Exp() {
		Vector2ExpContext _localctx = new Vector2ExpContext(Context, State);
		EnterRule(_localctx, 6, RULE_vector2Exp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 206;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NUMBER:
				{
				State = 204;
				numberExp();
				}
				break;
			case ID:
				{
				State = 205;
				variableExp();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 208;
			Match(T__21);
			State = 211;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NUMBER:
				{
				State = 209;
				numberExp();
				}
				break;
			case ID:
				{
				State = 210;
				variableExp();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EgoSettingExpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpContext numberExp() {
			return GetRuleContext<NumberExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VariableExpContext variableExp() {
			return GetRuleContext<VariableExpContext>(0);
		}
		public EgoSettingExpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_egoSettingExp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterEgoSettingExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitEgoSettingExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEgoSettingExp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EgoSettingExpContext egoSettingExp() {
		EgoSettingExpContext _localctx = new EgoSettingExpContext(Context, State);
		EnterRule(_localctx, 8, RULE_egoSettingExp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 213;
			Match(T__5);
			State = 214;
			Match(T__6);
			State = 217;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NUMBER:
				{
				State = 215;
				numberExp();
				}
				break;
			case ID:
				{
				State = 216;
				variableExp();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 219;
			Match(T__7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SimulationSettingExpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpContext numberExp() {
			return GetRuleContext<NumberExpContext>(0);
		}
		public SimulationSettingExpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_simulationSettingExp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterSimulationSettingExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitSimulationSettingExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSimulationSettingExp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SimulationSettingExpContext simulationSettingExp() {
		SimulationSettingExpContext _localctx = new SimulationSettingExpContext(Context, State);
		EnterRule(_localctx, 10, RULE_simulationSettingExp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 221;
			Match(T__22);
			State = 222;
			Match(T__6);
			State = 223;
			numberExp();
			State = 224;
			Match(T__7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionExpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdExpContext idExp() {
			return GetRuleContext<IdExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentListContext argumentList() {
			return GetRuleContext<ArgumentListContext>(0);
		}
		public FunctionExpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionExp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterFunctionExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitFunctionExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionExp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionExpContext functionExp() {
		FunctionExpContext _localctx = new FunctionExpContext(Context, State);
		EnterRule(_localctx, 12, RULE_functionExp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 226;
			idExp();
			State = 227;
			Match(T__6);
			State = 229;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 7008681536L) != 0)) {
				{
				State = 228;
				argumentList();
				}
			}

			State = 231;
			Match(T__7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrayExpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentListContext argumentList() {
			return GetRuleContext<ArgumentListContext>(0);
		}
		public ArrayExpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arrayExp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterArrayExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitArrayExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrayExp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrayExpContext arrayExp() {
		ArrayExpContext _localctx = new ArrayExpContext(Context, State);
		EnterRule(_localctx, 14, RULE_arrayExp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 233;
			Match(T__23);
			State = 235;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 7008681536L) != 0)) {
				{
				State = 234;
				argumentList();
				}
			}

			State = 237;
			Match(T__24);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ArgumentListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argumentList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterArgumentList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitArgumentList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgumentList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentListContext argumentList() {
		ArgumentListContext _localctx = new ArgumentListContext(Context, State);
		EnterRule(_localctx, 16, RULE_argumentList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 239;
			expression();
			State = 244;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__25) {
				{
				{
				State = 240;
				Match(T__25);
				State = 241;
				expression();
				}
				}
				State = 246;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentStmContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VariableExpContext variableExp() {
			return GetRuleContext<VariableExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public AssignmentStmContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignmentStm; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterAssignmentStm(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitAssignmentStm(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignmentStm(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentStmContext assignmentStm() {
		AssignmentStmContext _localctx = new AssignmentStmContext(Context, State);
		EnterRule(_localctx, 18, RULE_assignmentStm);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 247;
			variableExp();
			State = 248;
			Match(T__26);
			State = 249;
			expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableExpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdExpContext idExp() {
			return GetRuleContext<IdExpContext>(0);
		}
		public VariableExpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableExp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterVariableExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitVariableExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableExp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableExpContext variableExp() {
		VariableExpContext _localctx = new VariableExpContext(Context, State);
		EnterRule(_localctx, 20, RULE_variableExp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 251;
			idExp();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StringExpContext stringExp() {
			return GetRuleContext<StringExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpContext numberExp() {
			return GetRuleContext<NumberExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Vector2ExpContext vector2Exp() {
			return GetRuleContext<Vector2ExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PositionExpContext positionExp() {
			return GetRuleContext<PositionExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RoadExpContext roadExp() {
			return GetRuleContext<RoadExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArrayExpContext arrayExp() {
			return GetRuleContext<ArrayExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VariableExpContext variableExp() {
			return GetRuleContext<VariableExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConfigExpContext configExp() {
			return GetRuleContext<ConfigExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EgoSettingExpContext egoSettingExp() {
			return GetRuleContext<EgoSettingExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SimulationSettingExpContext simulationSettingExp() {
			return GetRuleContext<SimulationSettingExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpContext functionExp() {
			return GetRuleContext<FunctionExpContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 22, RULE_expression);
		try {
			State = 264;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,35,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 253;
				stringExp();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 254;
				numberExp();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 255;
				vector2Exp();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 256;
				positionExp(0);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 257;
				roadExp();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 258;
				arrayExp();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 259;
				variableExp();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 260;
				configExp();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 261;
				egoSettingExp();
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 262;
				simulationSettingExp();
				}
				break;
			case 11:
				EnterOuterAlt(_localctx, 11);
				{
				State = 263;
				functionExp();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentStmContext assignmentStm() {
			return GetRuleContext<AssignmentStmContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpContext functionExp() {
			return GetRuleContext<FunctionExpContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 24, RULE_statement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 268;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,36,Context) ) {
			case 1:
				{
				State = 266;
				assignmentStm();
				}
				break;
			case 2:
				{
				State = 267;
				functionExp();
				}
				break;
			}
			State = 270;
			Match(T__27);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ScenarioContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(AWSIMScriptGrammarParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ScenarioContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_scenario; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterScenario(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitScenario(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitScenario(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ScenarioContext scenario() {
		ScenarioContext _localctx = new ScenarioContext(Context, State);
		EnterRule(_localctx, 26, RULE_scenario);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 273;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 272;
				statement();
				}
				}
				State = 275;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==ID );
			State = 277;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringExpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(AWSIMScriptGrammarParser.STRING, 0); }
		public StringExpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stringExp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterStringExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitStringExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStringExp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StringExpContext stringExp() {
		StringExpContext _localctx = new StringExpContext(Context, State);
		EnterRule(_localctx, 28, RULE_stringExp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 279;
			Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberExpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(AWSIMScriptGrammarParser.NUMBER, 0); }
		public NumberExpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numberExp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterNumberExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitNumberExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberExp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberExpContext numberExp() {
		NumberExpContext _localctx = new NumberExpContext(Context, State);
		EnterRule(_localctx, 30, RULE_numberExp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 281;
			Match(NUMBER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdExpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(AWSIMScriptGrammarParser.ID, 0); }
		public IdExpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_idExp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.EnterIdExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAWSIMScriptGrammarListener typedListener = listener as IAWSIMScriptGrammarListener;
			if (typedListener != null) typedListener.ExitIdExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAWSIMScriptGrammarVisitor<TResult> typedVisitor = visitor as IAWSIMScriptGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdExp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdExpContext idExp() {
		IdExpContext _localctx = new IdExpContext(Context, State);
		EnterRule(_localctx, 32, RULE_idExp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 283;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 0: return positionExp_sempred((PositionExpContext)_localctx, predIndex);
		}
		return true;
	}
	private bool positionExp_sempred(PositionExpContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 4);
		case 1: return Precpred(Context, 3);
		case 2: return Precpred(Context, 2);
		case 3: return Precpred(Context, 1);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,34,286,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,1,0,1,0,1,0,1,0,1,0,3,0,40,8,0,3,0,42,8,0,1,0,1,0,
		1,0,1,0,3,0,48,8,0,1,0,1,0,1,0,1,0,3,0,54,8,0,1,0,1,0,1,0,1,0,3,0,60,8,
		0,1,0,1,0,1,0,1,0,3,0,66,8,0,3,0,68,8,0,1,0,1,0,1,0,1,0,3,0,74,8,0,1,0,
		1,0,1,0,1,0,3,0,80,8,0,1,0,1,0,1,0,1,0,3,0,86,8,0,1,0,1,0,1,0,1,0,3,0,
		92,8,0,5,0,94,8,0,10,0,12,0,97,9,0,1,1,1,1,1,1,1,1,1,1,3,1,104,8,1,1,1,
		1,1,3,1,108,8,1,1,1,1,1,1,1,3,1,113,8,1,1,1,1,1,1,1,1,1,3,1,119,8,1,1,
		1,1,1,1,1,1,1,3,1,125,8,1,1,1,3,1,128,8,1,1,2,1,2,1,2,1,2,1,2,3,2,135,
		8,2,1,2,1,2,1,2,1,2,1,2,1,2,3,2,143,8,2,1,2,1,2,1,2,1,2,1,2,1,2,3,2,151,
		8,2,1,2,1,2,1,2,1,2,1,2,1,2,3,2,159,8,2,1,2,1,2,1,2,1,2,1,2,1,2,3,2,167,
		8,2,1,2,1,2,1,2,1,2,1,2,1,2,3,2,175,8,2,1,2,1,2,1,2,1,2,1,2,1,2,3,2,183,
		8,2,1,2,1,2,1,2,1,2,1,2,1,2,3,2,191,8,2,1,2,1,2,1,2,1,2,1,2,1,2,3,2,199,
		8,2,1,2,1,2,3,2,203,8,2,1,3,1,3,3,3,207,8,3,1,3,1,3,1,3,3,3,212,8,3,1,
		4,1,4,1,4,1,4,3,4,218,8,4,1,4,1,4,1,5,1,5,1,5,1,5,1,5,1,6,1,6,1,6,3,6,
		230,8,6,1,6,1,6,1,7,1,7,3,7,236,8,7,1,7,1,7,1,8,1,8,1,8,5,8,243,8,8,10,
		8,12,8,246,9,8,1,9,1,9,1,9,1,9,1,10,1,10,1,11,1,11,1,11,1,11,1,11,1,11,
		1,11,1,11,1,11,1,11,1,11,3,11,265,8,11,1,12,1,12,3,12,269,8,12,1,12,1,
		12,1,13,4,13,274,8,13,11,13,12,13,275,1,13,1,13,1,14,1,14,1,15,1,15,1,
		16,1,16,1,16,0,1,0,17,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,0,
		0,330,0,67,1,0,0,0,2,127,1,0,0,0,4,202,1,0,0,0,6,206,1,0,0,0,8,213,1,0,
		0,0,10,221,1,0,0,0,12,226,1,0,0,0,14,233,1,0,0,0,16,239,1,0,0,0,18,247,
		1,0,0,0,20,251,1,0,0,0,22,264,1,0,0,0,24,268,1,0,0,0,26,273,1,0,0,0,28,
		279,1,0,0,0,30,281,1,0,0,0,32,283,1,0,0,0,34,35,6,0,-1,0,35,41,3,28,14,
		0,36,39,5,1,0,0,37,40,3,30,15,0,38,40,3,20,10,0,39,37,1,0,0,0,39,38,1,
		0,0,0,40,42,1,0,0,0,41,36,1,0,0,0,41,42,1,0,0,0,42,68,1,0,0,0,43,44,3,
		20,10,0,44,47,5,2,0,0,45,48,3,30,15,0,46,48,3,20,10,0,47,45,1,0,0,0,47,
		46,1,0,0,0,48,68,1,0,0,0,49,50,3,20,10,0,50,53,5,3,0,0,51,54,3,30,15,0,
		52,54,3,20,10,0,53,51,1,0,0,0,53,52,1,0,0,0,54,68,1,0,0,0,55,56,3,20,10,
		0,56,59,5,4,0,0,57,60,3,30,15,0,58,60,3,20,10,0,59,57,1,0,0,0,59,58,1,
		0,0,0,60,68,1,0,0,0,61,62,3,20,10,0,62,65,5,5,0,0,63,66,3,30,15,0,64,66,
		3,20,10,0,65,63,1,0,0,0,65,64,1,0,0,0,66,68,1,0,0,0,67,34,1,0,0,0,67,43,
		1,0,0,0,67,49,1,0,0,0,67,55,1,0,0,0,67,61,1,0,0,0,68,95,1,0,0,0,69,70,
		10,4,0,0,70,73,5,2,0,0,71,74,3,30,15,0,72,74,3,20,10,0,73,71,1,0,0,0,73,
		72,1,0,0,0,74,94,1,0,0,0,75,76,10,3,0,0,76,79,5,3,0,0,77,80,3,30,15,0,
		78,80,3,20,10,0,79,77,1,0,0,0,79,78,1,0,0,0,80,94,1,0,0,0,81,82,10,2,0,
		0,82,85,5,4,0,0,83,86,3,30,15,0,84,86,3,20,10,0,85,83,1,0,0,0,85,84,1,
		0,0,0,86,94,1,0,0,0,87,88,10,1,0,0,88,91,5,5,0,0,89,92,3,30,15,0,90,92,
		3,20,10,0,91,89,1,0,0,0,91,90,1,0,0,0,92,94,1,0,0,0,93,69,1,0,0,0,93,75,
		1,0,0,0,93,81,1,0,0,0,93,87,1,0,0,0,94,97,1,0,0,0,95,93,1,0,0,0,95,96,
		1,0,0,0,96,1,1,0,0,0,97,95,1,0,0,0,98,107,3,28,14,0,99,100,5,6,0,0,100,
		103,5,7,0,0,101,104,3,30,15,0,102,104,3,20,10,0,103,101,1,0,0,0,103,102,
		1,0,0,0,104,105,1,0,0,0,105,106,5,8,0,0,106,108,1,0,0,0,107,99,1,0,0,0,
		107,108,1,0,0,0,108,128,1,0,0,0,109,110,5,9,0,0,110,112,5,7,0,0,111,113,
		3,16,8,0,112,111,1,0,0,0,112,113,1,0,0,0,113,114,1,0,0,0,114,128,5,8,0,
		0,115,116,5,10,0,0,116,118,5,7,0,0,117,119,3,16,8,0,118,117,1,0,0,0,118,
		119,1,0,0,0,119,120,1,0,0,0,120,128,5,8,0,0,121,122,5,11,0,0,122,124,5,
		7,0,0,123,125,3,16,8,0,124,123,1,0,0,0,124,125,1,0,0,0,125,126,1,0,0,0,
		126,128,5,8,0,0,127,98,1,0,0,0,127,109,1,0,0,0,127,115,1,0,0,0,127,121,
		1,0,0,0,128,3,1,0,0,0,129,203,5,12,0,0,130,131,5,13,0,0,131,134,5,7,0,
		0,132,135,3,30,15,0,133,135,3,20,10,0,134,132,1,0,0,0,134,133,1,0,0,0,
		135,136,1,0,0,0,136,137,5,8,0,0,137,203,1,0,0,0,138,139,5,14,0,0,139,142,
		5,7,0,0,140,143,3,30,15,0,141,143,3,20,10,0,142,140,1,0,0,0,142,141,1,
		0,0,0,143,144,1,0,0,0,144,145,5,8,0,0,145,203,1,0,0,0,146,147,5,15,0,0,
		147,150,5,7,0,0,148,151,3,30,15,0,149,151,3,20,10,0,150,148,1,0,0,0,150,
		149,1,0,0,0,151,152,1,0,0,0,152,153,5,8,0,0,153,203,1,0,0,0,154,155,5,
		16,0,0,155,158,5,7,0,0,156,159,3,30,15,0,157,159,3,20,10,0,158,156,1,0,
		0,0,158,157,1,0,0,0,159,160,1,0,0,0,160,161,5,8,0,0,161,203,1,0,0,0,162,
		163,5,17,0,0,163,166,5,7,0,0,164,167,3,30,15,0,165,167,3,20,10,0,166,164,
		1,0,0,0,166,165,1,0,0,0,167,168,1,0,0,0,168,169,5,8,0,0,169,203,1,0,0,
		0,170,171,5,18,0,0,171,174,5,7,0,0,172,175,3,30,15,0,173,175,3,20,10,0,
		174,172,1,0,0,0,174,173,1,0,0,0,175,176,1,0,0,0,176,177,5,8,0,0,177,203,
		1,0,0,0,178,179,5,19,0,0,179,182,5,7,0,0,180,183,3,30,15,0,181,183,3,20,
		10,0,182,180,1,0,0,0,182,181,1,0,0,0,183,184,1,0,0,0,184,185,5,8,0,0,185,
		203,1,0,0,0,186,187,5,20,0,0,187,190,5,7,0,0,188,191,3,30,15,0,189,191,
		3,20,10,0,190,188,1,0,0,0,190,189,1,0,0,0,191,192,1,0,0,0,192,193,5,8,
		0,0,193,203,1,0,0,0,194,195,5,21,0,0,195,198,5,7,0,0,196,199,3,30,15,0,
		197,199,3,20,10,0,198,196,1,0,0,0,198,197,1,0,0,0,199,200,1,0,0,0,200,
		201,5,8,0,0,201,203,1,0,0,0,202,129,1,0,0,0,202,130,1,0,0,0,202,138,1,
		0,0,0,202,146,1,0,0,0,202,154,1,0,0,0,202,162,1,0,0,0,202,170,1,0,0,0,
		202,178,1,0,0,0,202,186,1,0,0,0,202,194,1,0,0,0,203,5,1,0,0,0,204,207,
		3,30,15,0,205,207,3,20,10,0,206,204,1,0,0,0,206,205,1,0,0,0,207,208,1,
		0,0,0,208,211,5,22,0,0,209,212,3,30,15,0,210,212,3,20,10,0,211,209,1,0,
		0,0,211,210,1,0,0,0,212,7,1,0,0,0,213,214,5,6,0,0,214,217,5,7,0,0,215,
		218,3,30,15,0,216,218,3,20,10,0,217,215,1,0,0,0,217,216,1,0,0,0,218,219,
		1,0,0,0,219,220,5,8,0,0,220,9,1,0,0,0,221,222,5,23,0,0,222,223,5,7,0,0,
		223,224,3,30,15,0,224,225,5,8,0,0,225,11,1,0,0,0,226,227,3,32,16,0,227,
		229,5,7,0,0,228,230,3,16,8,0,229,228,1,0,0,0,229,230,1,0,0,0,230,231,1,
		0,0,0,231,232,5,8,0,0,232,13,1,0,0,0,233,235,5,24,0,0,234,236,3,16,8,0,
		235,234,1,0,0,0,235,236,1,0,0,0,236,237,1,0,0,0,237,238,5,25,0,0,238,15,
		1,0,0,0,239,244,3,22,11,0,240,241,5,26,0,0,241,243,3,22,11,0,242,240,1,
		0,0,0,243,246,1,0,0,0,244,242,1,0,0,0,244,245,1,0,0,0,245,17,1,0,0,0,246,
		244,1,0,0,0,247,248,3,20,10,0,248,249,5,27,0,0,249,250,3,22,11,0,250,19,
		1,0,0,0,251,252,3,32,16,0,252,21,1,0,0,0,253,265,3,28,14,0,254,265,3,30,
		15,0,255,265,3,6,3,0,256,265,3,0,0,0,257,265,3,2,1,0,258,265,3,14,7,0,
		259,265,3,20,10,0,260,265,3,4,2,0,261,265,3,8,4,0,262,265,3,10,5,0,263,
		265,3,12,6,0,264,253,1,0,0,0,264,254,1,0,0,0,264,255,1,0,0,0,264,256,1,
		0,0,0,264,257,1,0,0,0,264,258,1,0,0,0,264,259,1,0,0,0,264,260,1,0,0,0,
		264,261,1,0,0,0,264,262,1,0,0,0,264,263,1,0,0,0,265,23,1,0,0,0,266,269,
		3,18,9,0,267,269,3,12,6,0,268,266,1,0,0,0,268,267,1,0,0,0,269,270,1,0,
		0,0,270,271,5,28,0,0,271,25,1,0,0,0,272,274,3,24,12,0,273,272,1,0,0,0,
		274,275,1,0,0,0,275,273,1,0,0,0,275,276,1,0,0,0,276,277,1,0,0,0,277,278,
		5,0,0,1,278,27,1,0,0,0,279,280,5,29,0,0,280,29,1,0,0,0,281,282,5,31,0,
		0,282,31,1,0,0,0,283,284,5,32,0,0,284,33,1,0,0,0,38,39,41,47,53,59,65,
		67,73,79,85,91,93,95,103,107,112,118,124,127,134,142,150,158,166,174,182,
		190,198,202,206,211,217,229,235,244,264,268,275
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
